services:
  catalogo.api:
    image: catalogo.api
    build:
      context: .
      dockerfile: Catalogo.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
